// Generated by typings
// Source: https://raw.githubusercontent.com/bigsan/common-any/6cca28dc84997f95dacb380dcbb8913e374d18e4/index.d.ts
declare module '~firebase/index' {
var _temp: any;
export default _temp;
}
declare module 'firebase/index' {
export { default } from '~firebase/index';
}
declare module 'firebase' {
export { default } from '~firebase/index';
}
